# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harlie Development Tools
email: joshua.riddell@gmail.com

dev_desc: "For feature requests and bug reports, please contact Josh:"
dev_email: joshua.riddell11@gmail.com
github_desc: >
  If you would like to contribute to the tools on this site check out
  the github repository:
github_url: https://github.com/JoshuaRiddell/harlie-tools/tree/gh-pages
linguist_desc: >
  For guidance on how to structure your conversations and to get involved in
  the harlie project, please contact Dr Christina Knuepffer:
linguist_email: c.knuepffer@uq.edu.au

description: > # this means to ignore newlines until "baseurl:"
  Some quick scripts developed to help with development of Harlie's
  conversational abilities.
baseurl: "/harlie-tools" # the subpath of your site, e.g. /blog
url: "http://joshuariddell.github.io" # the base hostname & protocol for your site
github_username:  joshuariddell

# Build settings
markdown: kramdown