# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harley Development Tools
email: joshua.riddell@gmail.com

dev_desc: "For feature requests and bug reports, please contact:"
dev_email: joshuariddell@gmail.com
linguist_desc: >
  For guidance on how to structure your conversations and to get involved in
  the harley project, please contact:
linguist_email: a.campbell@uq.edu.au
github_desc: >
  If you would like to contribute to the tools on this site check out
  the github repo:
github_url: https://github.com/JoshuaRiddell/harley-tools/tree/gh-pages

description: > # this means to ignore newlines until "baseurl:"
  Some quick scripts developed to help with development of Harley's
  conversational abilities.
baseurl: "/harley-tools" # the subpath of your site, e.g. /blog
url: "http://joshuariddell.github.io" # the base hostname & protocol for your site
github_username:  joshuariddell

# Build settings
markdown: kramdown